spring:
  datasource:
    url: jdbc:mysql://50.78.138.13:3306/xf
    username: root
    password: netmarch
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 9083

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名匹配

#logging:
#  level:
#    com:
#      netintech:
#        xfquartz:
#          dao: debug
#
#debug: true
